### ISSUE TITLE
Demo gives internal server error

### ISSUE THREAD

**Issue by enoch85** [nextcloud/passman#184]
1. Run the Demo @ demo.passman.cc
2. Go to https://demo.passman.cc:33540/index.php/apps/passman/ (45 minutes left atm)

@brantje Could you have a look?

**Comment by brantje** [comment]
Thanks for reporting it, seems that the ShareMiddleware is missing:
```
{"reqId":"z1GZCrkqfLksniGi0lyY","remoteAddr":"xxxxx","app":"index","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OCA\\\\Passman\\\\Middleware\\\\ShareMiddleware' not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Passman\\\\AppInfo\\\\Application->OCA\\\\Passman\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(437): Pimple\\\\Container->offsetGet('ShareMiddleware')\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->OC\\\\AppFramework\\\\DependencyInjection\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(361): Pimple\\\\Container->offsetGet('MiddlewareDispa...')\\n#4 \\\/var\\\/www\\\/html\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->OC\\\\AppFramework\\\\DependencyInjection\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(106): Pimple\\\\Container->offsetGet('Dispatcher')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('PageController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/passman\\\/')\\n#10 \\\/var\\\/www\\\/html\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/passman\\\/lib\\\/AppInfo\\\/Application.php\",\"Line\":65}","level":3,"time":"2017-01-07T11:19:40+00:00","method":"GET","url":"\/index.php\/apps\/passman\/","user":"--","version":"12.0.0.12"}
```
I'll update the image

**Comment by brantje** [comment]
Fixed!
